# Docker-compose file for running the application Laravel

services:
  app1_laravel_mysql:
    image: mysql
    container_name: app1_laravel_mysql
    ports:
      - "3339:3306"
    environment:
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - app1_laravel_mysql_data:/var/lib/mysql
    networks:
      - app1_laravel_network
  app1_laravel:
    depends_on:
      - app1_laravel_mysql
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app1_laravel
    ports:
      - "8089:80"
    environment:
      DB_HOST: app1_laravel_mysql
    volumes:
      - ./app:/app
    networks:
      - app1_laravel_network

volumes:
  app1_laravel_mysql_data:
    driver: local

networks:
  app1_laravel_network:
    driver: bridge
